### PR TITLE
Added Stars count

### LINKED ISSUE #53: Show the stars count in the page.

### PR DESCRIPTION
**Pull request by AK-007**
Fixes #53

### CODE REVIEW

**Comment by AK-007** [comment]
@aswanthkoleri Plz review.

**Comment by mubaris** [comment]
Link?

**Comment by AK-007** [comment]
Link : https://ak-007.github.io/OpenNews/

**Comment by aswanthkoleri** [comment]
@AK-007 Im not ale to click on button

**Comment by AK-007** [comment]
@aswanthkoleri what should happen on button click?I can implement it.

**Comment by aswanthkoleri** [comment]
@AK-007 It should redirect to my repo

**Comment by AK-007** [comment]
Okay

**Comment by AK-007** [comment]
@aswanthkoleri Plz review

**Comment by aswanthkoleri** [comment]
@AK-007 Nice :+1:

**Pull request merged**
