### PR TITLE
Solved issue#71.

### PR DESCRIPTION
**Pull request by shivhek25**

### CODE REVIEW

**Comment by shivhek25** [comment]
Live link : https://shivhek25.github.io/OpenNews/
@aswanthkoleri

**Comment by aswanthkoleri** [comment]
@shivhek25 Can you try a better design ? Take suggestions from codepen
Also change the border radius of Images in the cards.

**Comment by shivhek25** [comment]
sure.

**Comment by aswanthkoleri** [comment]
@shivhek25 This is fine

**Pull request merged**
