### PR TITLE
adding loader to website

### PR DESCRIPTION
**Pull request by ananya-agrawal**
pls guide me further

### CODE REVIEW

**Comment by aswanthkoleri** [comment]
@ananya-agrawal  Please provide the Live link

**Comment by ananya-agrawal** [comment]
https://ananya-agrawal.github.io/OpenNews/
@aswanthkoleri

**Comment by aswanthkoleri** [comment]
@ananya-agrawal The loader is not implemented properly.It should have a palin background.it shouldnt show the website.

**Comment by ananya-agrawal** [comment]
@aswanthkoleri i am aware of this and need help for the same. cant figure out how to solve it

**Comment by aswanthkoleri** [comment]
@ananya-agrawal  Read from [here](https://aswanthkoleri.github.io/blog/)

**Pull request closed without merging**
