### PR TITLE
added loader

### PR DESCRIPTION
**Pull request by ananya-agrawal**
@aswanthkoleri pls tell me is this way fine . Will try to add another one if this is the write way to do.

### CODE REVIEW

**Comment by ananya-agrawal** [comment]
https://ananya-agrawal.github.io/OpenNews/

**Comment by ananya-agrawal** [comment]
I just wanted to know is this the right way to add so that i could add something else dont want it to be merged

**Comment by aswanthkoleri** [comment]
@ananya-agrawal No this is not the way. It should like just a loader with a plain background color behind.No details of the site should be there in the background.

**Comment by ananya-agrawal** [comment]
https://codepen.io/Siddharth11/pen/xbGrpG?limit=all&page=3&q=loader
@aswanthkoleri can i change background color and add this as a loader

**Comment by mubaris** [comment]
@gauthamzz

**Comment by gauthamzz** [comment]
@mubaris 😸 
@aswanthkoleri be nice to contributers man 👍

**Pull request closed without merging**
